controller_manager_ns: ''
controller_list:
    - name: pmb2_arm_controller/arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - palbator_arm_column_joint
          - palbator_arm_shoulder_1_joint
          - palbator_arm_shoulder_2_joint
          - palbator_arm_shoulder_3_joint
          - palbator_arm_wrist_1_joint
          - palbator_arm_wrist_2_joint
          - palbator_arm_wrist_3_joint
          - palbator_arm_end_link