controller_list:
  - name: fake_pmb2_arm_controller
    joints:
      - palbator_arm_column_joint
      - palbator_arm_shoulder_1_joint
      - palbator_arm_shoulder_2_joint
      - palbator_arm_shoulder_3_joint
      - palbator_arm_wrist_1_joint
      - palbator_arm_wrist_2_joint
      - palbator_arm_wrist_3_joint
  - name: fake_pmb2_gripper_controller
    joints:
      - palbator_arm_wrist_3_joint
      - motor1_hand_joint
      - hand1_fingertip1_joint
      - hand1_fingertip2_joint
      - motor2_hand_joint
      - hand2_fingertip1_joint
      - hand2_fingertip2_joint